version: "3"
services:
  ai-app:
    build: .
    container_name: my-ai
    command: bash
    stdin_open: true
    tty: true
    environment:
      # AI Tool API Keys
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      
      # Optional: vibe-kanban Configuration (with defaults)
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-Ov23li9bxz3kKfPOIsGm}
      - POSTHOG_API_KEY=${POSTHOG_API_KEY:-}
      - POSTHOG_API_ENDPOINT=${POSTHOG_API_ENDPOINT:-}
      - HOST=${HOST:-0.0.0.0}
      - BACKEND_PORT=${BACKEND_PORT:-0}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - DISABLE_WORKTREE_ORPHAN_CLEANUP=${DISABLE_WORKTREE_ORPHAN_CLEANUP:-}
    volumes:
      - /var/services/homes/yoojinhyung/workspace:/workspace