version: '3.8'

services:
  ai-dev:
    build: .
    container_name: ai-dev-env
    ports:
      - "${EXTERNAL_PORT:-8100}:${PORT:-3001}"  # vibe-kanban web interface
    volumes:
      # Main workspace
      - ./workspace:/workspace
      
      # Repository storage for vibe-kanban
      - ./repos:/repos
      
      # Persistent data for vibe-kanban
      - ./data:/home/vibe/.local/share/vibe-kanban
      
      # SSH keys (if needed for git operations) - optional mount
      # Uncomment if you have SSH keys
      # - ~/.ssh:/home/vibe/.ssh:ro
      # - ~/.ssh:/root/.ssh:ro
      
      # Git config - optional mount
      # Uncomment if you have gitconfig
      # - ~/.gitconfig:/home/vibe/.gitconfig:ro
      # - ~/.gitconfig:/root/.gitconfig:ro
    
    environment:
      # Claude Code configuration
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      
      # Gemini CLI configuration  
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      
      # GitHub CLI configuration
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      
      # GitHub OAuth for vibe-kanban (optional)
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-Ov23li9bxz3kKfPOIsGm}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      
      # Port configuration
      - PORT=${PORT:-3001}
      - APP_PORT=${APP_PORT:-3001}
      - BACKEND_PORT=${BACKEND_PORT:-3001}
      - FRONTEND_PORT=${FRONTEND_PORT:-3001}
      
      # Host configuration
      - HOST=${HOST:-0.0.0.0}
      
      # Node environment
      - NODE_ENV=${NODE_ENV:-development}
      
      # Display for GUI apps (if needed)
      - DISPLAY=${DISPLAY:-:0}
      
      # PostHog Analytics (optional)
      - POSTHOG_API_KEY=${POSTHOG_API_KEY:-}
      - POSTHOG_API_ENDPOINT=${POSTHOG_API_ENDPOINT:-}
      
    stdin_open: true
    tty: true
    
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge