version: '3.8'

services:
  vibe-kanban:
    build: .
    image: vibe-kanban-npx:latest
    container_name: vibe-kanban
    ports:
      - "${EXTERNAL_PORT:-8100}:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-Ov23li9bxz3kKfPOIsGm}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      - BACKEND_PORT=3001
      - FRONTEND_PORT=3001
    volumes:
      - ./data:/root/.local/share/vibe-kanban
      - /var/services/homes/yoojinhyung/workspace:/repos:rw
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s