version: '3.8'

services:
  vibe-kanban:
    build: .
    image: vibe-kanban-npx:latest
    container_name: vibe-kanban
    ports:
      - "${EXTERNAL_PORT:-8100}:${APP_PORT:-3000}"
    environment:
      - HOST=0.0.0.0
      - PORT=${APP_PORT:-3000}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-Ov23li9bxz3kKfPOIsGm}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      - BACKEND_PORT=${BACKEND_PORT:-3001}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      # Database path
      - DATABASE_URL=sqlite:///app/data/vibe-kanban.db
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - /var/services/homes/yoojinhyung/workspace:/repos
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:${APP_PORT:-3000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s