version: '3.8'

services:
  # Enhanced vibe-kanban with additional tools
  vibe-kanban:
    build: .
    image: vibe-kanban:v1.0
    platform: linux/amd64
    container_name: vibe-kanban
    ports:
      - "8100:3001"
    environment:
      - HOST=0.0.0.0
      - PORT=3001
      # GitHub OAuth settings (optional)
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID:-}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET:-}
      # PostHog analytics (optional)
      - POSTHOG_API_KEY=${POSTHOG_API_KEY:-}
      - POSTHOG_HOST=${POSTHOG_HOST:-https://app.posthog.com}
      # Database path
      - DATABASE_URL=sqlite:///app/data/vibe-kanban.db
    volumes:
      - ./data:/app/data
      - /var/services/homes/yoojinhyung/workspace:/repos
      - ./config:/app/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s