version: '3.8'

services:
  # Alternative 1: Use Docker Hub image (if available)
  vibe-kanban:
    image: vibekanban/vibe-kanban:latest
    container_name: vibe-kanban
    ports:
      - "8100:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - DATABASE_URL=sqlite:///app/data/vibe-kanban.db
    volumes:
      - ./data:/app/data
      - ./repos:/repos
      - ./config:/app/config
    restart: unless-stopped

  # Alternative 2: Use a similar kanban tool (Planka)
  # planka:
  #   image: ghcr.io/plankanban/planka:latest
  #   container_name: planka
  #   ports:
  #     - "1337:1337"
  #   environment:
  #     - BASE_URL=http://localhost:1337
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres/planka
  #     - SECRET_KEY=your-secret-key
  #   volumes:
  #     - ./data:/app/public/user-avatars
  #     - ./data:/app/public/project-background-images
  #     - ./data:/app/private/attachments
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped
  
  # postgres:
  #   image: postgres:14-alpine
  #   container_name: planka-postgres
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=planka
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   restart: unless-stopped